I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 51, in script
    $renpy.call(label=lista[count+1])
  File "game/script.rpy", line 51, in <module>
    $renpy.call(label=lista[count+1])
IndexError: list index out of range

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 51, in script
    $renpy.call(label=lista[count+1])
  File "renpy/ast.py", line 928, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "renpy/python.py", line 2245, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "game/script.rpy", line 51, in <module>
    $renpy.call(label=lista[count+1])
  File "renpy/python.py", line 992, in __getitem__
    rv = list.__getitem__(self, index)
IndexError: list index out of range

Windows-10-10.0.19041
Ren'Py 7.4.11.2266
ProjetoGame 1.0
Sun Jun 19 14:12:09 2022
